/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ManageIndexRouteImport } from './routes/manage.index'
import { Route as SamplesSampleIdRouteImport } from './routes/samples.$sampleId'
import { Route as ManageAllScansRouteImport } from './routes/manage.all-scans'
import { Route as AcquisitionsAcquisitionIdRouteImport } from './routes/acquisitions.$acquisitionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/manage/',
  path: '/manage/',
  getParentRoute: () => rootRouteImport,
} as any)
const SamplesSampleIdRoute = SamplesSampleIdRouteImport.update({
  id: '/samples/$sampleId',
  path: '/samples/$sampleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageAllScansRoute = ManageAllScansRouteImport.update({
  id: '/manage/all-scans',
  path: '/manage/all-scans',
  getParentRoute: () => rootRouteImport,
} as any)
const AcquisitionsAcquisitionIdRoute =
  AcquisitionsAcquisitionIdRouteImport.update({
    id: '/acquisitions/$acquisitionId',
    path: '/acquisitions/$acquisitionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRoute
  '/manage/all-scans': typeof ManageAllScansRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRoute
  '/manage/all-scans': typeof ManageAllScansRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/manage': typeof ManageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acquisitions/$acquisitionId': typeof AcquisitionsAcquisitionIdRoute
  '/manage/all-scans': typeof ManageAllScansRoute
  '/samples/$sampleId': typeof SamplesSampleIdRoute
  '/manage/': typeof ManageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acquisitions/$acquisitionId'
    | '/manage/all-scans'
    | '/samples/$sampleId'
    | '/manage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acquisitions/$acquisitionId'
    | '/manage/all-scans'
    | '/samples/$sampleId'
    | '/manage'
  id:
    | '__root__'
    | '/'
    | '/acquisitions/$acquisitionId'
    | '/manage/all-scans'
    | '/samples/$sampleId'
    | '/manage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcquisitionsAcquisitionIdRoute: typeof AcquisitionsAcquisitionIdRoute
  ManageAllScansRoute: typeof ManageAllScansRoute
  SamplesSampleIdRoute: typeof SamplesSampleIdRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/': {
      id: '/manage/'
      path: '/manage'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samples/$sampleId': {
      id: '/samples/$sampleId'
      path: '/samples/$sampleId'
      fullPath: '/samples/$sampleId'
      preLoaderRoute: typeof SamplesSampleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/all-scans': {
      id: '/manage/all-scans'
      path: '/manage/all-scans'
      fullPath: '/manage/all-scans'
      preLoaderRoute: typeof ManageAllScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acquisitions/$acquisitionId': {
      id: '/acquisitions/$acquisitionId'
      path: '/acquisitions/$acquisitionId'
      fullPath: '/acquisitions/$acquisitionId'
      preLoaderRoute: typeof AcquisitionsAcquisitionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcquisitionsAcquisitionIdRoute: AcquisitionsAcquisitionIdRoute,
  ManageAllScansRoute: ManageAllScansRoute,
  SamplesSampleIdRoute: SamplesSampleIdRoute,
  ManageIndexRoute: ManageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
